### ISSUE TITLE
Data Processing command wrong

### ISSUE THREAD

**Issue by LahElr** [FomalhautB/KM-BART-ACL#1]
Hello, I found that for the processing of visual gnome dataset, you are using the srcipt scripts.prepare_vcg. Is that a wrong command?
Also, I found the option for scripts.prepare_sbu --num_gpus should be --gpu_num.

**Comment by procedure2012** [comment]
Yes, it’s our mistake. It should be “scripts.prepare_vg”. We have fixed these mistakes. Thank you very much.
