### ISSUE TITLE
Problems found while repeating

### ISSUE THREAD

**Issue by LahElr** [FomalhautB/KM-BART-ACL#2]
Hi, I'v been repeating your works this days,and I have found some problems:
* For prepare coco reasoning and SBU reasoning, there should be a --model_file param but you did't mention it in the document.
* Preparing SBU reasoning need dataloaders from comet, which need executing make_atomic_data_loader.py in comet, but you did't mention it in the document.
* I've found that due to new modules in latest spacy, when loading language models from spacy, lemmatizer should be added in the disable list.
I would appreciate if you can add informations above to your documents for others trying repeating your work in future.
And I have also found that running filter_reason reports it need a json file called reason_train.json, which seems to be the output file of prepare_sbu_reason, but in different name. Is that truly a name mismatch or there's something I've not noticed?

**Comment by procedure2012** [comment]
Thank you for pointing out the problems. I have updated the README.

- `--model_file` is in Data Preparation->Reasoning (SBU and COCO)->step 4
- I add an instruction about the dataloader in Data Preparation->Reasoning (SBU and COCO)->step 1
- I didn't meet this problem, but I'm glad to see you've solved it.

Yes, you are right. The output file of `prepare_sbu_reason` should be renamed `reason_train.json`. I also add this in Data Preparation->Reasoning (SBU and COCO)->step 4.
